controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController


joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50

arm_trajectory_controller:
  ros__parameters:
    joints:
      - joint_0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joint: joint_1
    allow_stalling: true
    stall_timeout: 1000.0