# Default initial positions for ArmPlate's ros2_control fake system

initial_positions:
  5thDof_mnt-v2_Revolute-11: 0
  6Thdof-v2_Revolute-43: 0
  GripperHousingFinal-v1_Slider-44: 0
  Part5linkkkk222-v2_Revolute-40: 0
  link1_mod-v3_Revolute-39: -1.572
  newUpp-v1_Revolute-17: 1.572
  redassm-v1_Revolute-35: -1.572