# Default initial positions for ArmPlate's ros2_control fake system

initial_positions:
  2ndDOFDDD-v1_Revolute-8: 1.572
  5thDof_mnt-v2_Revolute-11: 0
  6Thdof-v2_Revolute-12: 1.572
  Base_link1-v1_Revolute-1: 0.7
  gripperHousing-v2_Slider-13: 0
  lnk1assm-v2_Revolute-9: 0
  lnk2_assm-v2_Revolute-10: 0