# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.05
  allowed_goal_duration_margin: 0.1
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - nmotion_controller
    - servo_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Base_link1-v1_Revolute-1
      - 2ndDOFDDD-v1_Revolute-8

  nmotion_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - lnk1assm-v2_Revolute-9
      - lnk2_assm-v2_Revolute-10
      - 5thDof_mnt-v2_Revolute-11

  servo_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - 6Thdof-v2_Revolute-12
  hand_controller:
    type: GripperCommand
    joints:
      - gripperHousing-v2_Slider-13
    action_ns: gripper_cmd
    default: true