# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - stepper_controller
    - nmotion_controller
    - servo_controller
    - hand_controller

  stepper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - newUpp-v1_Revolute-17
      - redassm-v1_Revolute-35
  nmotion_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - link1_mod-v3_Revolute-39
      - Part5linkkkk222-v2_Revolute-40
      - 5thDof_mnt-v2_Revolute-11
  servo_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - 6Thdof-v2_Revolute-43
  hand_controller:
    type: GripperCommand
    joints:
      - GripperHousingFinal-v1_Slider-44
    action_ns: gripper_cmd
    default: true
    allow_stalling: true
    stall_timeout: 10.0