# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    stepper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    nmotion_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

stepper_controller:
  ros__parameters:
    action_ns: follow_joint_trajectory
    joints:
      - newUpp-v1_Revolute-17
      - redassm-v1_Revolute-35
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
nmotion_controller:
  ros__parameters:
    action_ns: follow_joint_trajectory
    joints:
      - link1_mod-v3_Revolute-39
      - Part5linkkkk222-v2_Revolute-40
      - 5thDof_mnt-v2_Revolute-11
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
servo_controller:
  ros__parameters:
    action_ns: follow_joint_trajectory
    joints:
      - 6Thdof-v2_Revolute-43
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    action_ns: gripper_cmd
    joint: GripperHousingFinal-v1_Slider-44